<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Okay</name>
   <tag></tag>
   <elementGuidId>70af2d2a-c05d-4c1b-aaa7-a910a3c18fe3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modalBtn_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='modalBtn_btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Okay&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6ffade6a-f2ba-4778-866c-879742b8508a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modalBtn_btn</value>
      <webElementGuid>f12463dc-485e-4add-b0d8-1967b77b8606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>773cb283-66d1-43b7-aad0-4a99a3a265f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Okay
</value>
      <webElementGuid>c634f15b-3d58-4515-bbbb-94e089ff9867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalBtn_btn&quot;)</value>
      <webElementGuid>aae20ce0-94d6-4563-be5e-4c8c28b196ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='modalBtn_btn']</value>
      <webElementGuid>c0b1cc94-be2c-4311-975d-9744a8b2ef9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-button-primary-large[@id='modalBtn']/button</value>
      <webElementGuid>e0f56d9d-e917-4a5f-8c0f-e6cc599ccaae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EPF will make zakat payments'])[1]/following::button[1]</value>
      <webElementGuid>5de0797b-9280-4592-b8b0-1500f092e89a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Okay']/parent::*</value>
      <webElementGuid>937b1fd6-5d26-412c-a0c2-88a65bbd99a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/app-button-primary-large/button</value>
      <webElementGuid>a989d63c-d1c4-445f-803f-a665340ca3a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'modalBtn_btn' and @type = 'button' and (text() = ' Okay
' or . = ' Okay
')]</value>
      <webElementGuid>a6789638-df96-4426-82ab-75d787dcdfb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
