<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Accept</name>
   <tag></tag>
   <elementGuidId>d337f7c2-c8e6-42dd-93f9-3e140c05cdcc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#profileDetailsProfileDetailsTncAccept_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='profileDetailsProfileDetailsTncAccept_btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Accept&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b171c970-b941-458b-8ea5-3906379fa3fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profileDetailsProfileDetailsTncAccept_btn</value>
      <webElementGuid>30e0da29-76b7-4574-af68-6c238f1d7ede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b6d4b9ff-85cc-4c98-b0d4-615dfe80419e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Accept
</value>
      <webElementGuid>dfc59a52-df6a-4edf-ab90-c35704f3f54d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profileDetailsProfileDetailsTncAccept_btn&quot;)</value>
      <webElementGuid>472d5009-3de4-4d11-88ba-5f16bc676390</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='profileDetailsProfileDetailsTncAccept_btn']</value>
      <webElementGuid>d0590fda-1d4f-431c-bdd9-945f231ca7fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-button-primary-large[@id='profileDetailsProfileDetailsTncAccept']/button</value>
      <webElementGuid>656677d6-c724-4206-90f7-e6f27fff11c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Akad declaration &amp; Terms and Conditions'])[1]/following::button[1]</value>
      <webElementGuid>ab3d7d20-c95d-4d5e-808f-75107789b0f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Out'])[1]/following::button[1]</value>
      <webElementGuid>4a3daf46-2998-4a9b-9847-e8926ed070ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Decline'])[1]/preceding::button[1]</value>
      <webElementGuid>a93613fb-68b5-46b5-a07c-be54b46e1086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EN'])[2]/preceding::button[2]</value>
      <webElementGuid>cf2a70b3-75b8-4120-ba62-728302aad5e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Accept']/parent::*</value>
      <webElementGuid>759f73db-4207-4359-ace3-29a6d6da643a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-button-primary-large/button</value>
      <webElementGuid>55732fdf-2a88-4e39-9518-3d8d517e584b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'profileDetailsProfileDetailsTncAccept_btn' and @type = 'button' and (text() = ' Accept
' or . = ' Accept
')]</value>
      <webElementGuid>20b99c2c-519d-4964-99a9-8f0e6c9f69ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
