<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>OkayButton</name>
   <tag></tag>
   <elementGuidId>4e24bcdd-88c0-43e8-8a80-42fbd37ad925</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <locatorCollection>
      <entry>
         <key>ANDROID_UI_AUTOMATOR</key>
         <value>new UiSelector()</value>
      </entry>
      <entry>
         <key>ID</key>
         <value>com.mip.sit.epf:id/iAkaunPage.coachmark.1.Primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>ACCESSIBILITY</key>
         <value>com.mip.sit.epf:id/CoolingPeriodPage.done.button.Primary</value>
      </entry>
   </locatorCollection>
   <locatorStrategy>ACCESSIBILITY</locatorStrategy>
   <platform>ANDROID</platform>
</MobileElementEntity>
