<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Register Nomination</name>
   <tag></tag>
   <elementGuidId>944cc02c-b981-4e4d-a02b-8242a980fe5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='nominationRegisterHeader_btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nominationRegisterHeader_btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Register Nomination&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5267727e-43a0-481c-a6ac-7477489d5c15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nominationRegisterHeader_btn</value>
      <webElementGuid>657c34a1-c320-459e-8fd0-765333647a88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f13bda50-70ec-4ceb-b91a-f6e81d6d93fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Register Nomination
</value>
      <webElementGuid>d746b27d-fca5-426c-afff-4bd5447df518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nominationRegisterHeader_btn&quot;)</value>
      <webElementGuid>9d68b0a8-7ef4-4f15-9097-6ff89e8d6c91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='nominationRegisterHeader_btn']</value>
      <webElementGuid>fc4a61fc-a82e-4d54-b368-e45dd75f1b5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-button-primary-large[@id='nominationRegisterHeader']/button</value>
      <webElementGuid>0d499e97-58e6-4139-a52a-3f292336a15c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Protect your legacy with a nomination'])[1]/following::button[1]</value>
      <webElementGuid>c490cd1d-0b1d-4117-9384-e5893b40ad54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomination'])[1]/following::button[1]</value>
      <webElementGuid>09709da9-50a5-4eaf-a036-297f60420382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EN'])[2]/preceding::button[1]</value>
      <webElementGuid>cf09047d-42a6-4403-8d82-a4d61ef273a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Register Nomination']/parent::*</value>
      <webElementGuid>86844eb8-4ec7-4b3c-b46e-56c230ff15ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-button-primary-large/button</value>
      <webElementGuid>608c6bb9-d171-4d1a-b6cd-0e4c15ab9ace</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'nominationRegisterHeader_btn' and @type = 'button' and (text() = ' Register Nomination
' or . = ' Register Nomination
')]</value>
      <webElementGuid>b1d77740-cce7-4d69-b23c-5e0913efd29c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
