<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Nominate Now</name>
   <tag></tag>
   <elementGuidId>733f9da7-cdfe-44fd-bd38-8cc979bef6bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modalPrimaryBtn_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='modalPrimaryBtn_btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Nominate Now&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>92f1a7be-fbea-48c6-856c-d214d14c5786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modalPrimaryBtn_btn</value>
      <webElementGuid>de5f5657-42e3-4d75-950b-fb2e8e3fc5d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c8846a58-dbb7-47c2-b723-a6414a8b471a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Nominate Now
</value>
      <webElementGuid>78b4c462-d78e-4800-aaf6-45581d6bc235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalPrimaryBtn_btn&quot;)</value>
      <webElementGuid>1bd538b3-701e-4e74-82e2-5f38c335f6a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='modalPrimaryBtn_btn']</value>
      <webElementGuid>284ab4a8-2d9c-4c5d-80db-9ed129ff8479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-button-primary-large[@id='modalPrimaryBtn']/button</value>
      <webElementGuid>7b1783ce-4993-4a02-9564-b490ec454cca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C'])[2]/following::button[1]</value>
      <webElementGuid>37000299-753c-478a-982a-cb127fcac842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maybe Later'])[1]/preceding::button[1]</value>
      <webElementGuid>c8520103-9afe-4ec3-9dd0-e50141853990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nominate Now']/parent::*</value>
      <webElementGuid>174c56fb-1c6f-4752-97af-4106b65cc01a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-button-primary-large/button</value>
      <webElementGuid>8072c0e7-5363-423b-b737-2145c624c747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'modalPrimaryBtn_btn' and @type = 'button' and (text() = ' Nominate Now
' or . = ' Nominate Now
')]</value>
      <webElementGuid>618ec50e-ad16-4970-98ce-d1ef52bbf5d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
