<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Nomination</name>
   <tag></tag>
   <elementGuidId>7abf80fe-2401-48d5-9e9f-e185df64633f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='nom'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>li >> internal:has-text=&quot;Nomination&quot;i >> #nom</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fd63ab3d-4514-45ba-bf9c-244c818d537d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nom</value>
      <webElementGuid>1d9b3949-32a7-42fd-963c-ab06654d092d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item</value>
      <webElementGuid>cef33508-6dbb-4d5d-a8eb-dbc8641c5f66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nomination</value>
      <webElementGuid>90a4e748-2047-4728-b17e-6b8c38b2e145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[1]/app-root[1]/div[1]/app-profile-layout[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;wide-screen-layout&quot;]/div[@class=&quot;d-flex align-items-start justify-content-start w-100 main-page-width&quot;]/div[@class=&quot;card-wrap w-100&quot;]/app-profile[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;profile-main ng-star-inserted&quot;]/div[@class=&quot;right-section&quot;]/div[@class=&quot;right-inner-body&quot;]/div[@class=&quot;middle-bar ng-star-inserted&quot;]/div[@class=&quot;mobile-center&quot;]/ul[@class=&quot;nav d-flex flex-column tabs-section&quot;]/li[@class=&quot;nav-item&quot;]/div[@id=&quot;nom&quot;]</value>
      <webElementGuid>d71e9961-ea83-451d-9a65-79165bb1806a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='nom'])[2]</value>
      <webElementGuid>3bb79610-1297-4af6-86be-9ede421f4d73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Auto Transaction'])[1]/following::div[1]</value>
      <webElementGuid>c9e8955d-c207-47d2-85cd-c8dc0c7b071f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Details'])[1]/following::div[3]</value>
      <webElementGuid>9e33e286-0302-4477-a1bd-242c707c7af0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consent'])[1]/preceding::div[2]</value>
      <webElementGuid>cdab1bd4-77a1-4f3c-9a6c-ba07d3461396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div</value>
      <webElementGuid>c8eef0fc-4681-46ad-8172-363eb3337650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'nom' and (text() = 'Nomination' or . = 'Nomination')]</value>
      <webElementGuid>17d2d6bd-a4a1-4575-8e4a-08daae86b55b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
