<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continue_2</name>
   <tag></tag>
   <elementGuidId>ab05eff9-3677-48ed-8a14-349839285b3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='withdrawalBuy1HsePrevRecordContinueBtn_btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#withdrawalBuy1HsePrevRecordContinueBtn_btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Continue&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4f7e4ea6-9764-4019-b823-994a8e8ebba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>withdrawalBuy1HsePrevRecordContinueBtn_btn</value>
      <webElementGuid>8ac5c539-ba0e-4e89-ba5b-071c9dfe3d74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ff35c422-6939-4ad7-a97c-58b9dc0bde6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Continue
</value>
      <webElementGuid>181762b1-7099-4f33-a690-859059bceb2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;withdrawalBuy1HsePrevRecordContinueBtn_btn&quot;)</value>
      <webElementGuid>3cad8c60-c55d-443f-a993-a8a8babf3e84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='withdrawalBuy1HsePrevRecordContinueBtn_btn']</value>
      <webElementGuid>4dc19a58-d7a5-4967-ad90-0e302f124da9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-button-primary-large[@id='withdrawalBuy1HsePrevRecordContinueBtn']/button</value>
      <webElementGuid>4de2e31b-3b22-4e90-8092-11cbe8f8d6b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RM 209,340.00'])[1]/following::button[1]</value>
      <webElementGuid>1298d2cb-1454-467a-9583-dd17a9237ef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loan Amount'])[1]/following::button[1]</value>
      <webElementGuid>79fb31e9-0416-4f82-a33e-86fd3736a1ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EN'])[2]/preceding::button[1]</value>
      <webElementGuid>96186ad9-39e7-4d55-8bc4-54cb5b221cbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue']/parent::*</value>
      <webElementGuid>f8136fdd-3251-4e39-a867-d46a94efdcda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-button-primary-large/button</value>
      <webElementGuid>faa3280f-c732-4ce9-a845-c0bb103ed62c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'withdrawalBuy1HsePrevRecordContinueBtn_btn' and @type = 'button' and (text() = ' Continue
' or . = ' Continue
')]</value>
      <webElementGuid>1c445b06-8a8b-4373-b4a4-eea87dee32ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
