<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continue (2)</name>
   <tag></tag>
   <elementGuidId>b27bfcec-7e0a-4c60-aa8f-3b58f1c0781b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='withdrawalBuy1HseEnterDetailsSubmitBtn_btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#withdrawalBuy1HseEnterDetailsSubmitBtn_btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Continue&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6d59347c-59ac-45f2-9ee9-7237193553e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>withdrawalBuy1HseEnterDetailsSubmitBtn_btn</value>
      <webElementGuid>0183d657-5b2c-47be-8924-d875d6cdd683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7ead6d43-2c7d-40dc-a4c4-f80bf78c8a75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Continue
</value>
      <webElementGuid>4ca625c3-49b1-4673-8ca5-af6aa35161cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;withdrawalBuy1HseEnterDetailsSubmitBtn_btn&quot;)</value>
      <webElementGuid>d1f058b7-f71b-4f27-9fbf-d3cc8a616831</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='withdrawalBuy1HseEnterDetailsSubmitBtn_btn']</value>
      <webElementGuid>ecd5e1a6-9b69-4ce5-a860-ffcbd79f0070</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-button-primary-large[@id='withdrawalBuy1HseEnterDetailsSubmitBtn']/button</value>
      <webElementGuid>943880d2-0cef-497a-9566-21c0c93dd23b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The date of your agreement should not exceed 3 years.'])[1]/following::button[1]</value>
      <webElementGuid>561b5634-3f03-482a-bd12-d8598410a06a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sales &amp; Purchase Agreement Date'])[1]/following::button[2]</value>
      <webElementGuid>9d55ea32-2e8f-40a8-9f9d-9f221dc56dec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EN'])[2]/preceding::button[1]</value>
      <webElementGuid>a0cc0a0e-7c3d-4535-aefd-047ccdd07e03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue']/parent::*</value>
      <webElementGuid>77319649-393b-47d3-92a3-4371fb07e257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-button-primary-large/button</value>
      <webElementGuid>c0e50bbf-1dd4-42af-ad3b-6554fe76a587</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'withdrawalBuy1HseEnterDetailsSubmitBtn_btn' and @type = 'button' and (text() = ' Continue
' or . = ' Continue
')]</value>
      <webElementGuid>5bfd224c-6dfa-4268-ae15-5f81cdbad55c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
