<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address Line 1_address_line_2</name>
   <tag></tag>
   <elementGuidId>91647b7d-4799-47f8-8243-5b0d94f66f97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='address_line_2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#address_line_2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Address Line 2&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f509bc8b-e423-417b-82d7-4efacf89b19a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address_line_2</value>
      <webElementGuid>93e75d42-0911-4783-a837-fa5e7bf46678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>address_line_2</value>
      <webElementGuid>d17e04bf-c3f8-4741-80fe-3f1227570c7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c62-138 cdk-text-field-autofill-monitored ng-dirty ng-invalid ng-touched</value>
      <webElementGuid>d36f00fe-9a1e-451f-a6af-dcfefef087a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Address Line 2</value>
      <webElementGuid>65c47b09-da3a-4742-9bf8-ddf1bcca355d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Address Line 2</value>
      <webElementGuid>01057264-bde5-4d83-8dc6-52c267f76ee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>97f390aa-cc00-4e19-8a34-cc0e78fe0e87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-form-interact-field-id</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>cb190591-befc-43fa-88c6-647f1cb5ec17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address_line_2&quot;)</value>
      <webElementGuid>f906a392-861f-4574-9abf-3894cd946279</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='address_line_2']</value>
      <webElementGuid>6bf43844-fb5b-4f51-8d92-d8cab6564c7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-form-field[2]/div/div/div/input</value>
      <webElementGuid>cdd62897-b8a1-4f07-a4f6-1833c7b378ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'address_line_2' and @placeholder = 'Address Line 2']</value>
      <webElementGuid>5b295feb-c277-4a4e-bfdf-8c45b4e86a6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
