<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Type of Loan No_loanNumber</name>
   <tag></tag>
   <elementGuidId>beea3e8b-eef1-4baa-899e-ca04fd7702c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loanNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='loanNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Eg: 8293210238&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a7b8ec55-0518-4da6-9ae4-c2095baa4a6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>loanNumber</value>
      <webElementGuid>8a0b1030-e1ae-4fe4-84c1-bfa784ee387b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loanNumber</value>
      <webElementGuid>12df47d7-bdf8-4b75-80d8-9fee170f48e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Eg: 8293210238</value>
      <webElementGuid>050bfb35-2cd7-46fe-a7d6-9daf391adf5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>bec5f038-9ccd-48ac-85b6-b394b2fe5df7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c62-172 cdk-text-field-autofill-monitored ng-touched ng-dirty ng-invalid</value>
      <webElementGuid>6ba90cfa-4b29-46d6-bd00-86ce29403aa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^[0-9]*$</value>
      <webElementGuid>3259be03-2808-4e88-bb86-a4678b59c4df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Eg: 8293210238</value>
      <webElementGuid>e3f308e1-a1ae-4bd9-85f9-410f4987919e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>72bd659d-eb7c-4236-bbe9-64887db7ba46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-form-interact-field-id</name>
      <type>Main</type>
      <value>19</value>
      <webElementGuid>1ed20100-f542-423d-9747-c1457ed40aa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loanNumber&quot;)</value>
      <webElementGuid>41f52781-71fd-447e-81ec-38f162cf2f13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='loanNumber']</value>
      <webElementGuid>73b51cdb-54a0-410c-9cf6-71e411872ea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-form-field[5]/div/div/div/input</value>
      <webElementGuid>a0565360-096a-418a-ab2a-d93e0abe8146</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'loanNumber' and @placeholder = 'Eg: 8293210238']</value>
      <webElementGuid>0b2f1cc0-09ec-4625-ad2b-c4592c01d742</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
