<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_RM_loanAmount</name>
   <tag></tag>
   <elementGuidId>dc9f8373-2aac-4d3b-8661-bb7c15967000</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loanAmount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='loanAmount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;0.00&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aa2dd66c-4404-44b3-bf90-7444c12e1cfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>loanAmount</value>
      <webElementGuid>702a034a-7d35-4179-b173-80c41f4b45e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loanAmount</value>
      <webElementGuid>c8a11c53-2716-4fed-a65d-5f51f2fea042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>79933f8f-ac6e-46ab-84b4-b9d3e4141a50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-untouched ng-invalid cdk-text-field-autofill-monitored ng-dirty</value>
      <webElementGuid>e006c028-1743-4472-8889-61d7a85f7a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>5a4eee27-aa23-41f3-9e79-9f7c9ed52459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a26f98e3-bb61-4357-8016-517872c838d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>52025ff6-79d1-4160-a541-d2a39c655a0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loanAmount&quot;)</value>
      <webElementGuid>719abc9c-260d-46a0-b47a-41416c5e43f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='loanAmount']</value>
      <webElementGuid>a47209e3-110a-4a76-bf4b-beabb7f1b1f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-form-field[3]/div/div/div/div/input</value>
      <webElementGuid>865c2eca-be35-4b36-a89e-b60923fe0575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'loanAmount' and @placeholder = '0.00']</value>
      <webElementGuid>03094432-3fed-4dae-8c39-53cac5afd0ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
