<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Security</name>
   <tag></tag>
   <elementGuidId>b84887e2-9e74-43ff-b6c7-37723d8bb2fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sec']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sec</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>li >> internal:has-text=&quot;Security&quot;i >> #sec</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8a29cd76-edd1-40ae-9980-2d9146199751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sec</value>
      <webElementGuid>acc36e18-b092-4f65-8fa6-7217efc9a2d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item</value>
      <webElementGuid>2d198474-30ec-4bbd-831f-33f62ea62541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Security</value>
      <webElementGuid>eee9c83f-75c0-4c4d-bba7-3f1414e16d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[1]/app-root[1]/div[1]/app-profile-layout[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;wide-screen-layout&quot;]/div[@class=&quot;d-flex align-items-start justify-content-start w-100 main-page-width&quot;]/div[@class=&quot;card-wrap w-100&quot;]/app-profile[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;profile-main ng-star-inserted&quot;]/div[@class=&quot;right-section&quot;]/div[@class=&quot;right-inner-body&quot;]/div[@class=&quot;middle-bar ng-star-inserted&quot;]/div[@class=&quot;mobile-center&quot;]/ul[@class=&quot;nav d-flex flex-column tabs-section&quot;]/li[@class=&quot;nav-item&quot;]/div[@id=&quot;sec&quot;]</value>
      <webElementGuid>06020e17-1bd9-4560-8ff2-535f0c172d97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='sec']</value>
      <webElementGuid>3c36808a-957f-4fc6-b638-84fcc40775f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personalisation'])[1]/following::div[1]</value>
      <webElementGuid>f5348896-98a4-4537-8d2c-9cdb495afb33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consent'])[1]/following::div[3]</value>
      <webElementGuid>55371321-785c-4ca1-bf40-17e4afdfd743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage notifications'])[1]/preceding::div[2]</value>
      <webElementGuid>d7668635-6e46-4457-9808-d12eb1677a39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/div</value>
      <webElementGuid>a0db3924-0b24-494e-a7f4-878da56339a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'sec' and (text() = 'Security' or . = 'Security')]</value>
      <webElementGuid>6c17c6ee-8ed6-43ca-9a35-a049c9416af8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
