<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_i-Sayang</name>
   <tag></tag>
   <elementGuidId>bfc1862e-7880-4e1a-bfcd-b8d6e8695a07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='i-Sayang']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#i-Sayang</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#i-Sayang</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>81b6fe9f-479d-4b3b-b9ff-50d0ce812573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-body text-center ng-star-inserted</value>
      <webElementGuid>8a21f57f-1556-4425-aef7-e52fc350d50d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>i-Sayang</value>
      <webElementGuid>8a0d3b6a-98fd-493d-97fc-5e68ace4faf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>i-Sayang</value>
      <webElementGuid>ce0ee896-5cb8-4566-8393-c38b478dc844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>i-Sayang</value>
      <webElementGuid>6fc5c178-0417-4a10-807b-17fb929e7b37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i-Sayang&quot;)</value>
      <webElementGuid>8d30fa65-1418-48b4-b9d9-d0ecb4423405</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='i-Sayang']</value>
      <webElementGuid>67845a75-7e12-4446-8484-3c9a843ad3a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Age'])[1]/following::a[1]</value>
      <webElementGuid>466ccb02-a3ce-4aa0-8fa6-026812bfcd48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Health'])[1]/following::a[2]</value>
      <webElementGuid>ca99e18d-27e4-43ba-bad6-489bb7c7377b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Withdraw your savings'])[1]/preceding::a[1]</value>
      <webElementGuid>3525e1d0-43d6-4b98-97f4-5e7a93496ff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/a</value>
      <webElementGuid>94c94753-1336-4825-a5c5-1c54d182705f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'i-Sayang' and @name = 'i-Sayang' and (text() = 'i-Sayang' or . = 'i-Sayang')]</value>
      <webElementGuid>2370eb77-f3e8-4912-b8dd-78506d7def82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
