<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continue</name>
   <tag></tag>
   <elementGuidId>87d757be-9d87-4b3e-8022-2363e1eaf073</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#iSayangRegistrationImportantModalButton_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='iSayangRegistrationImportantModalButton_btn'] | //button[@id='iSayangRegistrationConfirmContinueBtn_btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Continue&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f4d7997b-729b-4648-ae2c-9ffd69af7193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iSayangRegistrationImportantModalButton_btn</value>
      <webElementGuid>7324eac0-963f-434f-aed8-ef912c7def17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1a31fe34-d0e0-41c2-8bcd-1d2d64b2bd76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Continue
</value>
      <webElementGuid>caf6733c-44e1-48e1-a6d4-48fa37be523e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iSayangRegistrationImportantModalButton_btn&quot;)</value>
      <webElementGuid>0323a4cb-3913-4204-aab3-d85b701f563e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='iSayangRegistrationImportantModalButton_btn']</value>
      <webElementGuid>730747f3-2b47-42d4-9637-ec1a5f9fdae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-button-primary-large[@id='iSayangRegistrationImportantModalButton']/button</value>
      <webElementGuid>43a5f8ae-f53b-43f0-a778-d13cc9aa49cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The MyKad Number of Recipient (Wife) provided is correct and accurate.'])[1]/following::button[1]</value>
      <webElementGuid>1be2ede6-0700-4763-b653-fc6dad1eabb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Member and Recipient (Wife) meet the requirement for eligibility.'])[1]/following::button[1]</value>
      <webElementGuid>577e3f11-5abc-4aea-8d92-ceaaad988149</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue']/parent::*</value>
      <webElementGuid>fd32c203-a102-4c3f-b1b2-6256a333dfa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/app-button-primary-large/button</value>
      <webElementGuid>097acaae-68ee-4fe6-8937-e8a8a2c0f60b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'iSayangRegistrationImportantModalButton_btn' and @type = 'button' and (text() = ' Continue
' or . = ' Continue
')]</value>
      <webElementGuid>788b01b6-1751-42eb-ae63-4aaa03732fa3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
