<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>5547bd5d-27ee-467e-b1a5-4fa0f952a82f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#iSayangRegistrationEnterNricSearcBtn_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='iSayangRegistrationEnterNricSearcBtn_btn'] | //button[@id='button-primary_btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Search&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>930c6464-600f-46dd-a096-049f2361333f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iSayangRegistrationEnterNricSearcBtn_btn</value>
      <webElementGuid>296523dd-8672-4283-881f-dfaa26b15bb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4a4f787d-2b9b-4191-8090-f7431b10d1b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Search
</value>
      <webElementGuid>23ac377b-a6d3-4ca9-9830-48f151b656d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iSayangRegistrationEnterNricSearcBtn_btn&quot;)</value>
      <webElementGuid>80ee5a56-2348-4d89-bd56-47c15ae42427</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='iSayangRegistrationEnterNricSearcBtn_btn']</value>
      <webElementGuid>87e84e69-9638-4f4d-b0b3-516e58003c58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-button-primary-large[@id='iSayangRegistrationEnterNricSearcBtn']/button</value>
      <webElementGuid>a3d99bf3-5843-4ed6-a913-bd1500f038f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Out'])[1]/following::button[1]</value>
      <webElementGuid>d2b752b1-a2db-4df1-b755-100772f9648c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear All'])[1]/preceding::button[1]</value>
      <webElementGuid>ef5f21cc-63b4-4b4c-8f3c-9e572b59952e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EN'])[2]/preceding::button[2]</value>
      <webElementGuid>c4a2cefc-71f4-4bda-ac4d-f865d820b9fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Search']/parent::*</value>
      <webElementGuid>3b4ce07f-1ad4-479b-af0d-c68aabce383f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-button-primary-large/button</value>
      <webElementGuid>bd29f492-f69d-403a-b0d2-38c3c9a7f967</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'iSayangRegistrationEnterNricSearcBtn_btn' and @type = 'button' and (text() = ' Search
' or . = ' Search
')]</value>
      <webElementGuid>e217a626-a191-43af-bcc9-49348fbbddd9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
