<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Okay</name>
   <tag></tag>
   <elementGuidId>a440daf2-f230-40d2-8c5e-87a6a222d17f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#withdrawal1MillionButtonsOkay_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='withdrawal1MillionButtonsOkay_btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Okay&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>88b97df2-9ca2-4ce4-b957-8fc99ddc3ee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>withdrawal1MillionButtonsOkay_btn</value>
      <webElementGuid>266f8ad3-4cf9-491a-9d37-f481b46df643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3ccfddb2-fb1f-4e55-be09-d39977783b96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Okay
</value>
      <webElementGuid>0a461920-d7b8-4385-bab7-86e2da4a5fbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;withdrawal1MillionButtonsOkay_btn&quot;)</value>
      <webElementGuid>5d5e4902-7cf5-4aed-b06f-2814148b5d7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='withdrawal1MillionButtonsOkay_btn']</value>
      <webElementGuid>1ee7a97c-994f-472c-9199-d747f071df97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-button-primary-large[@id='withdrawal1MillionButtonsOkay']/button</value>
      <webElementGuid>98356acf-eaf5-4090-a380-de263146797e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Application Checklist'])[1]/following::button[1]</value>
      <webElementGuid>76d02f58-103a-401d-9acc-c032b53bfb0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Okay']/parent::*</value>
      <webElementGuid>00b78f0f-642d-4fad-bb14-3c4b1957cca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/app-button-primary-large/button</value>
      <webElementGuid>96747cd4-14bc-4600-be75-0d6aee426d1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'withdrawal1MillionButtonsOkay_btn' and @type = 'button' and (text() = ' Okay
' or . = ' Okay
')]</value>
      <webElementGuid>7a7ad157-e073-4652-a5e4-1c61a61a3964</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
