<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Done</name>
   <tag></tag>
   <elementGuidId>f8a349d0-ced0-4267-8a60-2ab58df9e07a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#infoDetailsPageButton_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='infoDetailsPageButton_btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Done&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ebaddbc2-87de-4891-af9c-567ac21deb8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>infoDetailsPageButton_btn</value>
      <webElementGuid>ac78c41b-166c-4e6c-9d4e-f1b2a1d2082a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>391e55e2-e194-42f1-9424-e6777a7b96c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Done
</value>
      <webElementGuid>fdf95f6e-9a0c-4116-aeb5-88dc8fae9e14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;infoDetailsPageButton_btn&quot;)</value>
      <webElementGuid>03e02f7a-1d31-4259-87a9-3098b58fabf6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='infoDetailsPageButton_btn']</value>
      <webElementGuid>cc01feda-3a44-46fd-bb62-1cc6e51589cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-button-primary-large[@id='infoDetailsPageButton']/button</value>
      <webElementGuid>625ed1bb-0caf-4b9c-94f9-dc953576e35d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Now, let’s fill in your bank &amp; bill in details.'])[1]/following::button[1]</value>
      <webElementGuid>03a3761e-b056-4f16-8ee0-6fdfd9f6a5d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Out'])[2]/following::button[1]</value>
      <webElementGuid>89b58734-abb6-40b2-a596-ad50340ea0c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EN'])[3]/preceding::button[1]</value>
      <webElementGuid>3166b8ad-3dc5-4662-9807-3b5de5e727a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Done']/parent::*</value>
      <webElementGuid>39a6cbef-b955-4564-9181-bea69d48715e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-button-primary-large/button</value>
      <webElementGuid>d5b713ec-0ce9-4dcd-a396-6f221646deff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'infoDetailsPageButton_btn' and @type = 'button' and (text() = ' Done
' or . = ' Done
')]</value>
      <webElementGuid>d5401001-49c6-41b7-a825-fd2eb050d6d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
