<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continue (2)</name>
   <tag></tag>
   <elementGuidId>dd96f636-4540-4711-8977-f2e111eb2d8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#healthWithdrawalWithdrawingDetailContinueBtn_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='healthWithdrawalWithdrawingDetailContinueBtn_btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Continue&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>34c26d6f-cfa6-4c01-b57b-582fea9a72be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>healthWithdrawalWithdrawingDetailContinueBtn_btn</value>
      <webElementGuid>525fdb83-0305-4dd4-96df-77afc1b84c54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2c50bac7-ca30-4d5d-9202-097fa311ae2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Continue
</value>
      <webElementGuid>5633b501-8efd-4ee0-8229-72ae473179dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;healthWithdrawalWithdrawingDetailContinueBtn_btn&quot;)</value>
      <webElementGuid>7a3ae0c5-21c9-47d9-893d-bbf102251220</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='healthWithdrawalWithdrawingDetailContinueBtn_btn']</value>
      <webElementGuid>dbf8220f-ed49-44f5-a3c3-8090b397125b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-button-primary-large[@id='healthWithdrawalWithdrawingDetailContinueBtn']/button</value>
      <webElementGuid>4f39fdec-cd06-477f-a35f-1e09174c6b22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Critical Illness'])[1]/following::button[1]</value>
      <webElementGuid>417a4ba6-859b-43ab-8ac8-b7d9e8a8d217</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Medical Classification'])[1]/following::button[1]</value>
      <webElementGuid>1bc1e17c-eb07-4bea-8e7d-35f7e75f4f28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EN'])[2]/preceding::button[1]</value>
      <webElementGuid>660b5539-116a-4dfe-8c82-bde8da2f0dd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue']/parent::*</value>
      <webElementGuid>9be86596-b5d8-4a98-b726-b08abcafb108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-button-primary-large/button</value>
      <webElementGuid>fe49ce7a-8145-45b3-aaa4-b1c8e5b8ffd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'healthWithdrawalWithdrawingDetailContinueBtn_btn' and @type = 'button' and (text() = ' Continue
' or . = ' Continue
')]</value>
      <webElementGuid>61acf422-89da-4213-b1fd-be31ee32a036</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
