<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Health</name>
   <tag></tag>
   <elementGuidId>b45d76ac-2b8f-4b3a-8032-09aa798b99ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#i-Kasih > label.card-icon-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='i-Kasih']/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#i-Kasih</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>75f6c067-1aac-42ef-b648-f4f7c685292d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-icon-text</value>
      <webElementGuid>c1dbdda2-ccb0-4ea1-afdf-9ba1801cd463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>i-Kasih</value>
      <webElementGuid>506429c6-b456-4abe-b30c-e69677cd8d91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Health</value>
      <webElementGuid>f0a86839-ebfd-4ec6-809a-53628b1bf5d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i-Kasih&quot;)/label[@class=&quot;card-icon-text&quot;]</value>
      <webElementGuid>00eee0c1-1ab2-4d4d-9cc0-f089d5628e80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='i-Kasih']/label</value>
      <webElementGuid>4df8d4b8-7f2f-422a-afa2-41bc9419027e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Education'])[1]/following::label[1]</value>
      <webElementGuid>703b22bf-4f37-4c32-8cf3-806fd14abead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Housing'])[1]/following::label[2]</value>
      <webElementGuid>5444b4b5-248f-4fe3-9f6a-cd0e359c279f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Age'])[1]/preceding::label[1]</value>
      <webElementGuid>93409ce8-0e1d-4df9-a2ec-88c88a193462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='i-Sayang'])[1]/preceding::label[2]</value>
      <webElementGuid>8a4f5172-3e08-4307-9dbb-434ff755c3af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Health']/parent::*</value>
      <webElementGuid>369685f5-5f5d-44fa-8e1f-d93515fc16b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a/label</value>
      <webElementGuid>e33a3fda-c04f-4b58-ac27-61b9884f035e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Health' or . = 'Health')]</value>
      <webElementGuid>17054022-ac58-4356-b349-e5adf8d5c849</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
