<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continue (7)</name>
   <tag></tag>
   <elementGuidId>0f92465c-3b0f-4483-bee2-e7e0091cf1a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='withdrawalHseLoanMonInsLoanSubmitBtn_btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#withdrawalHseLoanMonInsLoanSubmitBtn_btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Continue&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>77bd9ac3-de0e-440f-8ff9-076e91d5d02f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>withdrawalHseLoanMonInsLoanSubmitBtn_btn</value>
      <webElementGuid>b2b3866a-e9a9-4d30-a0e1-ffb1c810a272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>271ef908-c432-4470-ae3c-be8b809273cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Continue
</value>
      <webElementGuid>4cc42a60-eab0-48b5-8a6d-6bc90ae6e8a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;withdrawalHseLoanMonInsLoanSubmitBtn_btn&quot;)</value>
      <webElementGuid>2aa0e7b8-0ab2-4064-b2f1-98bedb78408e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='withdrawalHseLoanMonInsLoanSubmitBtn_btn']</value>
      <webElementGuid>d87eed78-100b-4636-b519-1526090bbce1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-button-primary-large[@id='withdrawalHseLoanMonInsLoanSubmitBtn']/button</value>
      <webElementGuid>956b2ff1-d584-4fe8-b0d0-9ab1e2e15829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loan Approval Date'])[1]/following::button[2]</value>
      <webElementGuid>57a87957-e77a-4457-a6cf-9a1ec40f8ecb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loan Account No.'])[1]/following::button[2]</value>
      <webElementGuid>bec2dfec-6b86-4fcb-8aea-13a8564336d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EN'])[2]/preceding::button[1]</value>
      <webElementGuid>0cedaaa4-6d2c-4ee2-836f-e271e4e60b5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue']/parent::*</value>
      <webElementGuid>03da607c-3a78-415b-9d57-c8b0cf4d3205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-button-primary-large/button</value>
      <webElementGuid>4b35c8cd-75c4-4973-babe-676560e25202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'withdrawalHseLoanMonInsLoanSubmitBtn_btn' and @type = 'button' and (text() = ' Continue
' or . = ' Continue
')]</value>
      <webElementGuid>3c943abc-1db9-45ce-9e2d-11fb7ad32c42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
