<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Accept (1)</name>
   <tag></tag>
   <elementGuidId>c6ab3baf-e3c6-4c27-9974-96af6172c5f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='withdrawalHseLoanMonInsTncAcceptBtn_btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#withdrawalHseLoanMonInsTncAcceptBtn_btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Accept&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>495be5b6-6574-4875-a993-5a7b42ca4a45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>withdrawalHseLoanMonInsTncAcceptBtn_btn</value>
      <webElementGuid>e664b077-4818-4987-911c-b624d8326f69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>32fefc11-0783-4d6d-89a2-9677710ecf88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Accept
</value>
      <webElementGuid>3bef785e-004d-4a44-b14d-4f2e72c6d233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;withdrawalHseLoanMonInsTncAcceptBtn_btn&quot;)</value>
      <webElementGuid>9c293bd6-ef05-412e-80c6-9fb752e81a71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='withdrawalHseLoanMonInsTncAcceptBtn_btn']</value>
      <webElementGuid>1d87ec04-f9f8-4093-81d5-6bdd27c740ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-button-primary-large[@id='withdrawalHseLoanMonInsTncAcceptBtn']/button</value>
      <webElementGuid>60598ac2-3d39-41b0-98c5-666d745d615d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Decline'])[1]/preceding::button[1]</value>
      <webElementGuid>e90b5dc5-cc48-4ed3-9abe-0050b230e074</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EN'])[2]/preceding::button[2]</value>
      <webElementGuid>4b57810c-53cf-4dd2-ad5a-004844266ca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Accept']/parent::*</value>
      <webElementGuid>b7fc147e-1b5d-4b40-b99f-f65e255c8510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-button-primary-large/button</value>
      <webElementGuid>3ddb1bfb-0524-4d96-83a3-3c9a070dab4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'withdrawalHseLoanMonInsTncAcceptBtn_btn' and @type = 'button' and (text() = ' Accept
' or . = ' Accept
')]</value>
      <webElementGuid>302f8ebd-2fd8-421f-8e4a-fc3dc367061c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
