<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Monthly Instalment Applied_numberOfMonths</name>
   <tag></tag>
   <elementGuidId>03064f61-8a61-4612-8b13-5b772b8a0c71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#numberOfMonths</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='numberOfMonths']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter number of month&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fdf3ca72-c911-4354-94e8-bfc38431350b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>1d58d961-9766-4b9b-af18-4d53d8b40138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>numberOfMonths</value>
      <webElementGuid>14cf7be6-9e0d-45df-86b2-99b55104708d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>numberOfMonths</value>
      <webElementGuid>a74baa95-a819-491e-a18f-356691d1257e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c62-10 ng-untouched ng-pristine ng-invalid cdk-text-field-autofill-monitored</value>
      <webElementGuid>c467d142-47b4-446e-b21e-1abc0946f8b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter number of month</value>
      <webElementGuid>d4780136-48a0-45f2-96c7-89c5a292e7a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>999</value>
      <webElementGuid>31c99f98-065e-4ab7-be44-df1285b415ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Enter number of month</value>
      <webElementGuid>ab0a9b86-6775-4b57-9258-1d02c4232d0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>94c76766-b6de-4a78-9b12-fb3caac4c334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;numberOfMonths&quot;)</value>
      <webElementGuid>319665c2-7a73-4abc-8bc8-4a121f236ef1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='numberOfMonths']</value>
      <webElementGuid>2aaf3be3-bd02-481a-94ff-bf0bd3c986c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-form-field[2]/div/div/div/input</value>
      <webElementGuid>535e2ab8-bc70-4a01-ae53-fc843180bee9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'numberOfMonths' and @placeholder = 'Enter number of month']</value>
      <webElementGuid>0accb659-dd33-491a-8ce5-736d1996eb39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
