<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-option_Developer</name>
   <tag></tag>
   <elementGuidId>8cbe9f8d-9c37-4203-8f73-e0497ffa77e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-option-161</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='propertyType-panel']/mat-option</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Developer&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-option</value>
      <webElementGuid>97e18080-06c9-432a-a8e6-3de9552859f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>1082a83b-d664-4f4f-aa1b-625f5ac64cc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>DEVELOPER</value>
      <webElementGuid>cd40efb3-871d-4d65-84c5-fe249dbe60d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-option mat-focus-indicator mat-active ng-tns-c87-41</value>
      <webElementGuid>abfd0602-b569-4b86-86df-3bacbf781749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-option-161</value>
      <webElementGuid>c5f54aaa-8efe-44f0-b8d4-217959369e01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b5332be6-4d76-48a5-ab4a-7cf4014343a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7891c122-cf74-4be9-be5d-01da3a9d7df1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Developer </value>
      <webElementGuid>59cc6c8b-a9d2-48bd-8553-623055e54ddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-161&quot;)</value>
      <webElementGuid>a8afab69-028e-4e8d-b408-ff5b50d5a423</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-161']</value>
      <webElementGuid>15276787-5add-48b4-bdf0-b9fa27ce46d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='propertyType-panel']/mat-option</value>
      <webElementGuid>8db59d37-a268-48a7-aa54-d6085557282b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EN'])[2]/following::mat-option[1]</value>
      <webElementGuid>67f29564-86d9-4a54-a7f0-4ba178a08a66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue'])[1]/following::mat-option[1]</value>
      <webElementGuid>ffcb66f3-8bf2-4e18-aeaa-b394b13fdca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Individual'])[1]/preceding::mat-option[1]</value>
      <webElementGuid>d0ea3c98-7485-49a5-9411-ed5d2f827b26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option</value>
      <webElementGuid>b3be40b5-2efb-4879-ba30-9568195c8017</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-option[@id = 'mat-option-161' and (text() = ' Developer ' or . = ' Developer ')]</value>
      <webElementGuid>ed8e5952-3f2d-47d4-b79c-f56c9f031e44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
