<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Education</name>
   <tag></tag>
   <elementGuidId>8f3da084-a728-423c-a163-b438fe64d0e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='EDUCATION'] | (.//*[normalize-space(text()) and normalize-space(.)='Education'])</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#EDUCATION</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#EDUCATION</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e5ff2451-84ba-47f4-87c1-96afa82a4fb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-item ng-star-inserted</value>
      <webElementGuid>786d62f5-6f32-47a0-93b6-e0e91eea7815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EDUCATION</value>
      <webElementGuid>ec6ce048-69a5-471e-bb8f-c585312c7383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Education</value>
      <webElementGuid>147140b7-1a5d-4191-8f43-1858a1afded3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EDUCATION&quot;)</value>
      <webElementGuid>e6949829-53dc-4902-953e-ecb93861fd51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='EDUCATION']</value>
      <webElementGuid>7dcb3016-1903-4bbe-abb0-3232d7e43fac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buy/Build House'])[1]/following::div[1]</value>
      <webElementGuid>469c3393-2deb-4d20-b2f7-924764e5a4b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Akaun Fleksibel'])[1]/following::div[2]</value>
      <webElementGuid>0eb9dab8-81e1-4bdf-a71a-d2e9874061bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Health'])[1]/preceding::div[1]</value>
      <webElementGuid>b0388b5a-72a3-4da2-aedd-1e6ea6e25110</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]</value>
      <webElementGuid>098065e3-d224-48b0-a61e-7929809a6b7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'EDUCATION' and (text() = 'Education' or . = 'Education')]</value>
      <webElementGuid>b0a3a0db-8677-4b07-baf2-0d89cba0432e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
