<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_YesNo</name>
   <tag></tag>
   <elementGuidId>f1ecb53e-756a-4fe4-9dcc-c270f194ecf7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mat-select-value-29']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-select-value-29</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#mat-select-value-29</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e6d43caf-ddf7-4a58-b7d8-4d0707d8213c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-value ng-tns-c87-39</value>
      <webElementGuid>45f09952-454c-4fa6-b3ac-3adb1ecb59f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-select-value-29</value>
      <webElementGuid>dec25890-f742-4783-83eb-c9f5de53c919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yes/No</value>
      <webElementGuid>ce91aeb0-9916-4b76-a779-7655b57500bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-select-value-29&quot;)</value>
      <webElementGuid>2103c0f0-270a-4c52-acaa-ce39fd79c1f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mat-select-value-29']</value>
      <webElementGuid>1b16a8ba-f5bd-43b9-ba4c-7836fccc9045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-select[@id='ptpk_funding']/div/div</value>
      <webElementGuid>1a98f041-302f-4ec0-a8fe-221de5295049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Did you obtain education funding from PTPK?'])[1]/following::div[5]</value>
      <webElementGuid>03c2be4c-54d7-4b78-a759-d58a99fb2edf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACADEMY FOR HUMAN CAPITAL'])[1]/following::div[14]</value>
      <webElementGuid>20aaf1b7-d184-4279-8c02-a0200a1b8a4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Start Date'])[1]/preceding::div[7]</value>
      <webElementGuid>e4f3cf57-23ce-49d8-a80a-7e01c2034941</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/mat-form-field/div/div/div/mat-select/div/div</value>
      <webElementGuid>be720532-680f-4bc5-aad8-deffd97f0a93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mat-select-value-29' and (text() = 'Yes/No' or . = 'Yes/No')]</value>
      <webElementGuid>4becd4a3-e348-4cf2-aec8-7306b9d65d62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
