<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_RM_pay_to_institution</name>
   <tag></tag>
   <elementGuidId>818a2f24-8e09-4701-90c5-5188d7eae9ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pay_to_institution</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pay_to_institution']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;0&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3c95127d-e22e-4545-a6a2-6d25e6e3c726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6f0b6ac1-5896-4f21-a43b-13d45c0dbb20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pay_to_institution</value>
      <webElementGuid>63fb140f-aacb-42bf-8ffa-fd088c90ff07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>pay_to_institution</value>
      <webElementGuid>e3413187-a5e6-4312-a6ff-07aba683f188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b71f7576-dc2b-4393-86fc-167705361040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-invalid cdk-text-field-autofill-monitored ng-dirty ng-touched</value>
      <webElementGuid>787848a7-c343-4ee3-9395-53d010829760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>da2a9413-78c6-435e-95fa-13e8369da304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>26c35072-c286-4e80-bd1c-46ba54600d9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>112cf003-2cb9-454e-b5bb-0e05e6761e4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pay_to_institution&quot;)</value>
      <webElementGuid>8ce6556d-5238-4c4e-9f5c-aa98c4bd2c3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pay_to_institution']</value>
      <webElementGuid>5666a319-39e5-4a37-8603-bb60b23654e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='education']/div[2]/form/div/div[2]/div/mat-form-field/div/div/div/div/input</value>
      <webElementGuid>38acb525-f6eb-4a24-93d1-aabc149b66ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a33e5d3a-2eaf-45e5-937f-c808564fca0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'pay_to_institution' and @placeholder = '0']</value>
      <webElementGuid>38b95f63-0f0c-413f-bd74-40b686c24a8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
