<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-option_Johor Bahru</name>
   <tag></tag>
   <elementGuidId>93cae2b1-3f31-45ed-a297-54d26c5f5c6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-option[@id='mat-option-144']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-option-144</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Johor Bahru&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-option</value>
      <webElementGuid>b62acc5c-ef19-4a18-8d37-d9458e9672b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>55259374-1e82-4eed-889a-b28287bad5a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-option mat-focus-indicator ng-star-inserted ng-tns-c87-37</value>
      <webElementGuid>4ad8cd1d-38fa-4a27-a5bf-2b07afd5c290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-option-144</value>
      <webElementGuid>485e5b48-197c-41fd-82d4-98733c0aa639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6e511a03-92e6-4476-902a-ca1523ae8d06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fed16d4f-653c-4149-a872-e8421052b65b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Johor Bahru</value>
      <webElementGuid>8c8ede19-0991-45e4-9c52-6853fac713a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-144&quot;)</value>
      <webElementGuid>097dbc05-82f3-4918-9d4c-966d4f740576</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-144']</value>
      <webElementGuid>ede28091-3108-4d31-8320-9ba3ad5eed38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='epf_branch-panel']/mat-option[2]</value>
      <webElementGuid>30b29d93-bfca-443c-a228-58e65ff17786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EPF Branch'])[2]/following::mat-option[1]</value>
      <webElementGuid>7d485bb6-9955-4d9b-9ea7-19a5e874c146</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EN'])[2]/following::mat-option[2]</value>
      <webElementGuid>ba46851b-5214-4bee-9d58-498bdafde43e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batu Pahat'])[1]/preceding::mat-option[1]</value>
      <webElementGuid>42a0252b-f7b4-4648-a441-a05141550421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option[2]</value>
      <webElementGuid>1738e8b0-4e58-4f47-9816-ade9aae02b57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-option[@id = 'mat-option-144' and (text() = 'Johor Bahru' or . = 'Johor Bahru')]</value>
      <webElementGuid>599f85e1-6656-4a12-b218-10b113e48bc0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
