<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Set a date</name>
   <tag></tag>
   <elementGuidId>6f04610f-5fd9-46f6-b8f0-c27ebf9d1f22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#monthPickerConfirm_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='monthPickerConfirm_btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Set a date&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bd5c842f-fa3b-4cd8-97d6-a08ea1201c31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>monthPickerConfirm_btn</value>
      <webElementGuid>c9452f41-4cc5-4e97-a905-84a6980e44f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f838c9c8-d635-42a7-9135-d960a7a04abc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Set a date
</value>
      <webElementGuid>4a1fafdf-8f17-494e-9fcd-deef5622554c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;monthPickerConfirm_btn&quot;)</value>
      <webElementGuid>2c1b7fbe-5d4f-4776-ac4f-ab2cf4235881</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='monthPickerConfirm_btn']</value>
      <webElementGuid>74a39f21-6264-4ebd-b84f-59137db3ff98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-button-primary-large[@id='monthPickerConfirm']/button</value>
      <webElementGuid>a7dd639a-0750-4e8c-987e-9f12c23eff7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jul'])[1]/following::button[1]</value>
      <webElementGuid>8b7b7399-d948-4835-b306-e51775e125fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Effective month'])[1]/following::button[1]</value>
      <webElementGuid>1f8a9bfb-70b1-4a5c-b7e2-4066ea95c97f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Month'])[1]/preceding::button[1]</value>
      <webElementGuid>b5e925f0-4915-4d2e-8b04-3efb39ff46fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue'])[1]/preceding::button[1]</value>
      <webElementGuid>a0cc7c9d-e7ad-497f-8828-f335fe372e68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Set a date']/parent::*</value>
      <webElementGuid>e6727fff-578f-4874-acda-8926185c9d1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-button-primary-large/button</value>
      <webElementGuid>581063cf-a5a3-4713-8c99-c6341aae9460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'monthPickerConfirm_btn' and @type = 'button' and (text() = ' Set a date
' or . = ' Set a date
')]</value>
      <webElementGuid>8bdc8b97-881e-4530-9c1e-21019951ec7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
