<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Confirm</name>
   <tag></tag>
   <elementGuidId>2bb58f38-973d-40bd-8c24-6068f2d6f00a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modalPrimaryBtn_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='modalPrimaryBtn_btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Confirm&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f73c32ba-401e-4de7-8612-afb4452dbd56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modalPrimaryBtn_btn</value>
      <webElementGuid>75def580-addb-4b34-af3d-c9c97e5360a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d698fdd9-f6d8-49ef-b348-f271553a26c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Confirm
</value>
      <webElementGuid>d9afa2d7-aa37-4dff-b3cd-115acc156db5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalPrimaryBtn_btn&quot;)</value>
      <webElementGuid>9b253b38-dd1e-4d85-badd-44b61897e755</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='modalPrimaryBtn_btn']</value>
      <webElementGuid>8f052820-3347-40c0-85a3-a148c7faf43c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-button-primary-large[@id='modalPrimaryBtn']/button</value>
      <webElementGuid>ba4f442b-d783-4016-ac13-0ceef0e63a89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='i-Topup application submission'])[1]/following::button[1]</value>
      <webElementGuid>4720e31a-4dab-4c5c-8fa8-6868378bb99a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/preceding::button[1]</value>
      <webElementGuid>a502553c-dab5-4590-aa52-3df2c4278bad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Confirm']/parent::*</value>
      <webElementGuid>ebaa246b-5ff9-42d5-a199-2ea5ce4ff423</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/app-button-primary-large/button</value>
      <webElementGuid>3ddc64e0-05a1-4e8f-8c9e-15b64c64590a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'modalPrimaryBtn_btn' and @type = 'button' and (text() = ' Confirm
' or . = ' Confirm
')]</value>
      <webElementGuid>7a15fae2-0ee9-4a88-b388-fbb339d726e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
