<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Confirm  Submit</name>
   <tag></tag>
   <elementGuidId>1e4e77e7-52a9-42ae-94d2-81197f95f1f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#contributionButtonAccept_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='contributionButtonAccept_btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Confirm &amp; Submit&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>230d4ba3-e5d1-4d22-9c34-4456a39ba7eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>contributionButtonAccept_btn</value>
      <webElementGuid>2df2302f-f62b-4f48-960f-98ad369d9b27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0b756653-7aad-4b5f-922b-0bdc19e63cad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Confirm &amp; Submit
</value>
      <webElementGuid>85d35152-9d9b-444b-be64-b1c68879989a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contributionButtonAccept_btn&quot;)</value>
      <webElementGuid>963e4cab-77db-4452-95e1-99a9d00a5b0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='contributionButtonAccept_btn']</value>
      <webElementGuid>7256ac6e-7729-400e-8890-7e6bc4b54004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-button-primary-large[@id='contributionButtonAccept']/button</value>
      <webElementGuid>3615b782-39e0-4a23-9544-648f184c4c54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms and Conditions.'])[1]/following::button[1]</value>
      <webElementGuid>d56d17a6-b411-4352-a035-97daf79d455d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/following::button[1]</value>
      <webElementGuid>fef7c591-1e16-463a-9039-7e2a5c10f0a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EN'])[2]/preceding::button[1]</value>
      <webElementGuid>c3587cf0-e9fd-4bf0-9dac-27e10175a08c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Confirm &amp; Submit']/parent::*</value>
      <webElementGuid>e5767bb7-0f6c-4f11-97fa-70704fda89ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-button-primary-large/button</value>
      <webElementGuid>28261b93-cbd1-485c-a40f-1ace8a61efff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'contributionButtonAccept_btn' and @type = 'button' and (text() = ' Confirm &amp; Submit
' or . = ' Confirm &amp; Submit
')]</value>
      <webElementGuid>cbb33271-3f3f-4c0c-a0a0-cabf5b982a45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
