<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continue_2</name>
   <tag></tag>
   <elementGuidId>d486d32e-f8b9-48f5-96ed-30c5a46bef1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='withdrawalHseLoanMonInsPrevRecordContinueBtn_btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#withdrawalHseLoanMonInsPrevRecordContinueBtn_btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Continue&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1cc790f9-6e5a-405b-9eab-ddd1fecabdd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>withdrawalHseLoanMonInsPrevRecordContinueBtn_btn</value>
      <webElementGuid>d0d40b4d-34eb-4b86-a1b1-553924356446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f4390a5f-141f-4fc5-ad66-5fb869bbaf9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Continue
</value>
      <webElementGuid>85de6234-8ff6-4fc8-b10d-833e3c87a6be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;withdrawalHseLoanMonInsPrevRecordContinueBtn_btn&quot;)</value>
      <webElementGuid>b02d25be-be79-412c-8c94-23f8e3a54d81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='withdrawalHseLoanMonInsPrevRecordContinueBtn_btn']</value>
      <webElementGuid>e1b430c5-fcbf-4189-8ed7-65a87ea6f44e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-button-primary-large[@id='withdrawalHseLoanMonInsPrevRecordContinueBtn']/button</value>
      <webElementGuid>6ecc020f-8faa-415e-afb5-33435cde13b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RM 209,340.00'])[1]/following::button[1]</value>
      <webElementGuid>613d0809-c430-43b3-9375-93ba902d3232</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loan Amount'])[1]/following::button[1]</value>
      <webElementGuid>7476e9fc-5450-44ed-bfaf-227dea0fa63a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EN'])[2]/preceding::button[1]</value>
      <webElementGuid>c41f9e22-4056-492a-9ad3-742df186e556</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue']/parent::*</value>
      <webElementGuid>54c0da89-4b52-49cb-81fe-e567c5fd81ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-button-primary-large/button</value>
      <webElementGuid>1e9e8c72-3122-4046-bb19-3862b376d1f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'withdrawalHseLoanMonInsPrevRecordContinueBtn_btn' and @type = 'button' and (text() = ' Continue
' or . = ' Continue
')]</value>
      <webElementGuid>3f3caf15-31bd-40fc-86fe-b4a68e7b89dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
