<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_RM_loanAmount</name>
   <tag></tag>
   <elementGuidId>c6192339-bf6b-4330-bd72-c25836efbe90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loanAmount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='loanAmount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;0.00&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>efec95e7-41db-40e8-b537-8969db86707b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>loanAmount</value>
      <webElementGuid>fbd37e6f-36b5-4b92-964d-22e9ea32376b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loanAmount</value>
      <webElementGuid>ec326fa4-1668-4359-a6aa-0e977ac8841e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>6d87192e-c523-41e5-a24b-8bda5c3dd9c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-invalid cdk-text-field-autofill-monitored ng-dirty ng-touched</value>
      <webElementGuid>218f1360-67bb-43b3-8bab-a5dd32eee43e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>c6773efa-e037-48e6-ba2b-877670dd0a38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>eff0b9e2-3c5a-460d-8f57-2cd538fcbe34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d754c203-1ea0-429d-9dad-45209e4af167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loanAmount&quot;)</value>
      <webElementGuid>cd4e5222-eec7-44ed-903b-0918d9947d63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='loanAmount']</value>
      <webElementGuid>893811a3-1c32-443d-8120-fc0954ebc5f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-form-field[2]/div/div/div/div/input</value>
      <webElementGuid>215ad135-05de-4160-a768-5377c3aeda55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'loanAmount' and @placeholder = '0.00']</value>
      <webElementGuid>99ec3e00-fe01-4d92-8c22-083966eb3fb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
