<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-option_Self</name>
   <tag></tag>
   <elementGuidId>81a01175-b9c9-482a-8844-33ff92536b17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-option-7192</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='transactionType-panel']/mat-option</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Self&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-option</value>
      <webElementGuid>fdc1702c-6024-4317-8e8f-9ffa589bd127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>e2a5f705-d81c-444d-900d-85e8e9fcf0d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-option mat-focus-indicator mat-active ng-tns-c87-89 ng-star-inserted</value>
      <webElementGuid>b68d32a7-d6a3-43fb-9344-5da62a95c83c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-option-7192</value>
      <webElementGuid>486feb4c-a0ed-4adf-9f31-d8d351dcefc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7109cf63-6ecc-49cf-9894-2ac00650fe79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>59039d78-8850-479e-a2da-ffe5141fd6a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Self </value>
      <webElementGuid>b88f3672-d717-4ad2-a6a2-d96fdd23a711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-7192&quot;)</value>
      <webElementGuid>fdbdf40e-2e12-4b5a-8eb1-f69e90a1d09d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-7192']</value>
      <webElementGuid>fe4ee107-5bca-48d4-8444-ba0da91d9f1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='transactionType-panel']/mat-option</value>
      <webElementGuid>35891c6d-8e2f-493d-a6d2-924e85fa2704</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EN'])[2]/following::mat-option[1]</value>
      <webElementGuid>3e8cbd0a-1813-4e13-b2e4-77f64f45ea0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue'])[1]/following::mat-option[1]</value>
      <webElementGuid>12672168-a595-43a1-81c0-3bb7afb07dac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assist Spouse'])[1]/preceding::mat-option[1]</value>
      <webElementGuid>16d3a9e0-c8f6-48ff-8136-02a0349e4532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option</value>
      <webElementGuid>b439844d-7a19-43f4-b9fa-5864af08d834</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-option[@id = 'mat-option-7192' and (text() = ' Self ' or . = ' Self ')]</value>
      <webElementGuid>48a82d60-eec1-4f78-a080-56293b9be479</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
