<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Done</name>
   <tag></tag>
   <elementGuidId>4fa38434-4099-4a5c-ada8-c0411b31713b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#doneProf_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='doneProf_btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Done&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f497bce7-9642-4007-b182-0ec0d29fbc91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>doneProf_btn</value>
      <webElementGuid>745073d7-7c89-422c-b6ba-2c3ef8ff5cf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8d490d0a-5270-40ea-9afb-b56b59ad26b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Done
</value>
      <webElementGuid>a31cbfeb-4b73-4547-9b99-596b88956fb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;doneProf_btn&quot;)</value>
      <webElementGuid>2ea6aa07-e22d-45bb-845c-2d7482c8d050</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='doneProf_btn']</value>
      <webElementGuid>4a043926-81b1-438c-94a6-a82993e79ca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-button-primary-large[@id='doneProf']/button</value>
      <webElementGuid>945a44c5-1a30-41ec-9885-b9d0b8e185e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Slide 1 of 1'])[3]/following::button[1]</value>
      <webElementGuid>118df494-80d6-43fd-9e45-20db28d65b96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Done'])[2]/following::button[2]</value>
      <webElementGuid>5ae5fa71-1e63-46ef-843f-42db17736a2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/app-button-primary-large/button</value>
      <webElementGuid>81985c51-00e2-4d06-82aa-273736ff0c2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'doneProf_btn' and @type = 'button' and (text() = ' Done
' or . = ' Done
')]</value>
      <webElementGuid>25bd7ccf-d6e5-44a6-82cb-c9b51d7e542c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
