<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Update Now</name>
   <tag></tag>
   <elementGuidId>f87f08f1-52e1-4d27-a4a1-9b9cc4d6db9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#WebHome2_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='WebHome2_btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Update Now&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c6da9d90-6e90-430a-8c97-322a07804367</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>WebHome2_btn</value>
      <webElementGuid>49195470-b085-40fa-b44b-6eaced2220db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>88f37320-d93b-42da-b988-f483f6d32be4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Update Now
</value>
      <webElementGuid>7ba17802-467a-4a37-994f-bd6b9f0356ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;WebHome2_btn&quot;)</value>
      <webElementGuid>314cbaaf-7f82-4a79-8bd3-2dc825c36082</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='WebHome2_btn']</value>
      <webElementGuid>c42804c5-fd81-43e9-9c43-dedf24120c90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slide-ngb-slide-10']/div/div/div/app-button-primary-large/button</value>
      <webElementGuid>8a04939e-240c-4356-a9b7-a6397d6a7686</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hi ,'])[3]/following::button[1]</value>
      <webElementGuid>46038426-df5e-418f-b531-9d0e0f494b1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Slide 3 of 4'])[1]/following::button[1]</value>
      <webElementGuid>5d63aa8f-acd2-4fba-ae35-cbab441c5876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Slide 4 of 4'])[1]/preceding::button[1]</value>
      <webElementGuid>e7719666-fc13-4d70-bbc6-cbd224316542</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hi ,'])[4]/preceding::button[1]</value>
      <webElementGuid>d1499cbe-d615-41bc-97b3-c3b48e42e923</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Update Now']/parent::*</value>
      <webElementGuid>6f79d191-80a3-4fb2-8281-8eae0088eeb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/app-button-primary-large/button</value>
      <webElementGuid>39806d7f-5d14-4797-a92f-ca50cee39c66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'WebHome2_btn' and @type = 'button' and (text() = ' Update Now
' or . = ' Update Now
')]</value>
      <webElementGuid>bff126b2-277d-43b5-851e-03a30a6fa838</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
