<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_28310</name>
   <tag></tag>
   <elementGuidId>d80951c9-5a15-421a-94c3-041030fe9586</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-autocomplete-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mat-autocomplete-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=listbox[name=&quot;Postcode&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>94d0e899-c291-4745-94ba-55773f301368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>ec2bddb2-9d90-4f6e-83a7-a38b0aeb38fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-autocomplete-panel mat-autocomplete-visible ng-star-inserted</value>
      <webElementGuid>3b32eaad-d936-45cf-bf98-87e2633f3a9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-autocomplete-2</value>
      <webElementGuid>c066d9ac-6d0b-4a0f-99a4-88f3b64ae143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>mat-form-field-label-37</value>
      <webElementGuid>40cefd65-b377-4277-9d76-a2c9835e6051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 28310 </value>
      <webElementGuid>213a1c5b-a97f-4424-b307-1d7206a29c1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-autocomplete-2&quot;)</value>
      <webElementGuid>b3c4e4f2-2352-4df9-9373-6024ab8ba04c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mat-autocomplete-2']</value>
      <webElementGuid>1fedc3dc-bbdf-40f8-81e6-80e92f11f880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-2']/div</value>
      <webElementGuid>e079535c-dd52-4788-818e-4591de4cd054</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear All'])[1]/following::div[9]</value>
      <webElementGuid>51f2fd47-8558-4319-8ac4-e7c1b1c364fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::div[9]</value>
      <webElementGuid>076f6857-7106-452f-9fe7-965e0e2cd914</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div</value>
      <webElementGuid>1b3d3f09-0d52-48ea-94b2-9a33c276aa6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mat-autocomplete-2' and (text() = ' 28310 ' or . = ' 28310 ')]</value>
      <webElementGuid>a4bf21b5-d9aa-490b-b45c-a09c8017738a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
