<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_28310 (1)</name>
   <tag></tag>
   <elementGuidId>11398569-841d-4b78-b2ab-414a3fe2ae71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-autocomplete-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mat-autocomplete-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=listbox[name=&quot;Postcode&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a36c6f53-5a38-4c42-9d36-c9cbc92bc7a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>584dc710-494e-4ca3-aa2a-38f57c216c0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-autocomplete-panel mat-autocomplete-visible ng-star-inserted</value>
      <webElementGuid>5a8f26d7-6da4-4880-a5e6-10dacf9bba29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-autocomplete-2</value>
      <webElementGuid>bffd9872-1e6b-4d8d-8958-2dc19e2b46a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>mat-form-field-label-37</value>
      <webElementGuid>8b7661f4-9b2f-426f-a9bd-42f5d1271347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 28310 </value>
      <webElementGuid>5b4374b1-c90a-4b9e-a3c9-564cd3e1ef13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-autocomplete-2&quot;)</value>
      <webElementGuid>cc28c604-3721-4edb-a79e-2ad7f2d9ae9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mat-autocomplete-2']</value>
      <webElementGuid>42eb7fbe-aae1-452e-8d72-caf94739066a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-2']/div</value>
      <webElementGuid>e9f76db4-1870-409f-ac93-123c9d85a57e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear All'])[1]/following::div[9]</value>
      <webElementGuid>2f427928-2778-4da9-9b46-36c71be8394e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::div[9]</value>
      <webElementGuid>ea89fc90-024b-42e6-b8cf-30b3eb45a7cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div</value>
      <webElementGuid>c82962b8-d293-42af-8cc9-2eb75affffad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mat-autocomplete-2' and (text() = ' 28310 ' or . = ' 28310 ')]</value>
      <webElementGuid>a49550f8-d6cb-49bf-a850-5412377ac8d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
