<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Okey</name>
   <tag></tag>
   <elementGuidId>02ee8a2a-cefe-413c-868b-fdfc4d775a31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='withdrawalAge50ButtonsOkay_btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#withdrawalAge50ButtonsOkay_btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Okey&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>305ce5d4-d08f-4884-af01-9d2ee55014a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>withdrawalAge50ButtonsOkay_btn</value>
      <webElementGuid>21369417-06ee-4e9d-b96c-1f76c1172888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8eced9d2-91d2-4a94-94bc-ea0acbc3fee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Okey
</value>
      <webElementGuid>ae50d3ea-6792-41ae-9f79-ee6e1652115a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;withdrawalAge50ButtonsOkay_btn&quot;)</value>
      <webElementGuid>6b737d06-59d4-40ff-87e7-b14c25663095</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='withdrawalAge50ButtonsOkay_btn']</value>
      <webElementGuid>ee6cc9d4-2a52-4305-b4c2-28364fa6e967</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-button-primary-large[@id='withdrawalAge50ButtonsOkay']/button</value>
      <webElementGuid>594d1478-c333-47a7-b68e-d86e40ed6fa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaction Authorisation Code'])[1]/following::button[1]</value>
      <webElementGuid>06a3fc91-353c-4309-a3dc-d0373e9e8b6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Senarai semak permohonan'])[1]/following::button[1]</value>
      <webElementGuid>512ca921-6fe5-4d24-bea1-65bec4ebc95b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Okey']/parent::*</value>
      <webElementGuid>a096667b-b8fa-4d92-a05f-ddbe4b74ad98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/app-button-primary-large/button</value>
      <webElementGuid>fd55059c-8b5f-471f-8f46-2881f4bee60e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'withdrawalAge50ButtonsOkay_btn' and @type = 'button' and (text() = ' Okey
' or . = ' Okey
')]</value>
      <webElementGuid>f01dd1e5-4c1a-45ee-832b-f57a346d8b5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
