<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sahkan</name>
   <tag></tag>
   <elementGuidId>0f6b6039-7103-4eae-8e6a-e438f7b6ad97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='modalPrimaryBtn_btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#modalPrimaryBtn_btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Sahkan&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a62803c7-3add-4500-8781-4f215d607180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modalPrimaryBtn_btn</value>
      <webElementGuid>9e1dd433-453f-46b4-8749-1d6be7d25c3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bb6f7de5-da89-4575-9909-bba9bde52a10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Sahkan
</value>
      <webElementGuid>1a1cb9b4-0439-4cb9-97e9-fb80647b038c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalPrimaryBtn_btn&quot;)</value>
      <webElementGuid>0e3a7ab6-925a-4788-9fe7-d3ef7dd2b21b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='modalPrimaryBtn_btn']</value>
      <webElementGuid>b5bd8442-edcc-4a54-8b44-765416f860d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-button-primary-large[@id='modalPrimaryBtn']/button</value>
      <webElementGuid>fca2c6d3-c07c-4657-bdb7-369ff2a587d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sila pastikan alamat anda berada di Malaysia untuk memohon pengeluaran ini'])[1]/following::button[1]</value>
      <webElementGuid>f91328e3-cce9-416f-a8b6-665bb24ed893</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Peringatan'])[1]/following::button[1]</value>
      <webElementGuid>33b06f23-eaf1-43a3-ab56-a19672bca349</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali'])[1]/preceding::button[1]</value>
      <webElementGuid>45b64e93-731e-4700-a369-4cb10875ad42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sahkan']/parent::*</value>
      <webElementGuid>463a3087-db62-4902-9a37-70423182c42b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/app-button-primary-large/button</value>
      <webElementGuid>4a1e12c5-3d32-4a06-9576-53e42fc798e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'modalPrimaryBtn_btn' and @type = 'button' and (text() = ' Sahkan
' or . = ' Sahkan
')]</value>
      <webElementGuid>06621e30-6866-4372-9420-5d825287636a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
