<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Teruskan_pengeluaran</name>
   <tag></tag>
   <elementGuidId>ad29b7a8-ec44-4dd1-ab85-bdecd75d67e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='withdrawalAge50ButtonsContinue_btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#withdrawalAge50ButtonsContinue_btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Teruskan&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c85935d5-f735-4bdb-a4aa-fda3a522f252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>withdrawalAge50ButtonsContinue_btn</value>
      <webElementGuid>e4c193d4-72ba-4a2b-8fff-0a77e14af07a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>89d6df6a-8f77-4611-93dd-737b8a0ebaca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Teruskan
</value>
      <webElementGuid>0f90b66c-20ef-458e-a277-2cb07778b544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;withdrawalAge50ButtonsContinue_btn&quot;)</value>
      <webElementGuid>a5d070f5-1028-4ec9-b435-cabe43a87c60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='withdrawalAge50ButtonsContinue_btn']</value>
      <webElementGuid>897925ef-77d2-4f88-918d-48eba53d979a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-button-primary-large[@id='withdrawalAge50ButtonsContinue']/button</value>
      <webElementGuid>2a684a48-052a-4537-b7d7-fc407fa37dcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengeluaran Penuh dari Akaun Sejahtera'])[1]/following::button[1]</value>
      <webElementGuid>02f539de-461d-4648-8186-9dc57c323f4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih kategori pengeluaran'])[1]/following::button[1]</value>
      <webElementGuid>635a2df9-b0f5-484f-8375-ce22c4128514</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BM'])[2]/preceding::button[1]</value>
      <webElementGuid>4157733a-8cca-4fd0-b921-49db89291422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Teruskan']/parent::*</value>
      <webElementGuid>e66a8cfe-8876-435e-828e-b3bc0aafba4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-button-primary-large/button</value>
      <webElementGuid>4ddf9945-31a8-4787-8f41-23a9adef7414</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'withdrawalAge50ButtonsContinue_btn' and @type = 'button' and (text() = ' Teruskan
' or . = ' Teruskan
')]</value>
      <webElementGuid>8c22e8e5-e272-4aa6-8864-c3d87b5afa27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
