<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Done</name>
   <tag></tag>
   <elementGuidId>36519167-cd70-4fb0-8c84-7b9deb56f7e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#infoDetailsPageButton_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='infoDetailsPageButton_btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Done&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e61533f8-5497-46d9-82bb-22720c0cfa77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>infoDetailsPageButton_btn</value>
      <webElementGuid>06057b67-3ab5-4e88-baa2-271666d4b05c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3e7481d2-31d2-4a5f-a5c7-ec9084c0c40a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Done
</value>
      <webElementGuid>2deb006a-04f6-427c-b0ef-6e4c32645014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;infoDetailsPageButton_btn&quot;)</value>
      <webElementGuid>ea4a62b6-868c-44b4-b229-a160ca94b809</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='infoDetailsPageButton_btn']</value>
      <webElementGuid>91202c81-7084-4104-9626-2a7c9189f1c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-button-primary-large[@id='infoDetailsPageButton']/button</value>
      <webElementGuid>0cd4ff70-9d7c-4d10-a236-134222da98fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please choose or add your bank account details'])[1]/following::button[1]</value>
      <webElementGuid>84226ad1-08cd-495c-84f1-27dfdcc490fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Out'])[2]/following::button[1]</value>
      <webElementGuid>e7acb428-84b5-4b31-8335-3b66eafa0813</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EN'])[3]/preceding::button[1]</value>
      <webElementGuid>af379a8f-0b5f-49e0-8f93-2b036cef1b97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Done']/parent::*</value>
      <webElementGuid>b8a9c3c9-c4a3-4da9-95d0-7a96cb9fd078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-button-primary-large/button</value>
      <webElementGuid>8cf6034c-c5b3-446b-8523-7de963abc912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'infoDetailsPageButton_btn' and @type = 'button' and (text() = ' Done
' or . = ' Done
')]</value>
      <webElementGuid>b5a76027-53bf-41a1-84a0-c92c7cce522b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
