<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-option_UOB (M) BHD</name>
   <tag></tag>
   <elementGuidId>4b699c0e-23c2-42f1-b91b-14f5a96c01f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-option-194</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bank-panel']/mat-option[65]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;bank logo UOB (M) BHD&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-option</value>
      <webElementGuid>4478965e-231a-40bb-ac5e-eebc4327d627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>2fdb2dbf-0259-4e0e-b430-dc01febd3f93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-option mat-focus-indicator ng-tns-c87-13 ng-star-inserted</value>
      <webElementGuid>adbffce0-2e2b-417f-a03d-4fc68fd5b590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-option-194</value>
      <webElementGuid>b18a5e1d-d18c-4c5d-9159-34124638ba9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a72b1136-2b08-423c-8d06-19dbdb2e7a66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>aead08ee-e84a-492a-9c49-45058e2f1ae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> UOB (M) BHD </value>
      <webElementGuid>55e441bf-2d5a-448c-81a5-c44e6966b0dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-194&quot;)</value>
      <webElementGuid>c22d79a8-e8e6-4560-8373-380111ea75c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-194']</value>
      <webElementGuid>e78b3913-f601-4804-8d01-a2721e198c3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bank-panel']/mat-option[65]</value>
      <webElementGuid>c0e73733-64ee-4b10-984c-8b947595b7a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='STANDARD CHARTERED'])[1]/following::mat-option[1]</value>
      <webElementGuid>53a287bb-27cf-4b80-accb-144e946b09f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RHB BANK BHD'])[1]/following::mat-option[2]</value>
      <webElementGuid>1cd89d39-17a6-4d4e-bc51-9d42fb7a1904</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option[65]</value>
      <webElementGuid>f9552ffe-239d-4e98-8778-4f0598c8101b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-option[@id = 'mat-option-194' and (text() = ' UOB (M) BHD ' or . = ' UOB (M) BHD ')]</value>
      <webElementGuid>3e8ea06e-ff3c-4f5d-bb3d-c1f50e83586b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
